# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ElonNewBaiSiBDJ' do

pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.11'
pod 'SDWebImage', '~> 3.8.1'
pod 'SVProgressHUD', '~> 2.0.3'

end
